//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0202
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MDK0202Entities : DbContext
    {
        public MDK0202Entities()
            : base("name=MDK0202Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Материал_> Материал_ { get; set; }
        public virtual DbSet<Партнеры_> Партнеры_ { get; set; }
        public virtual DbSet<ПродуктыПартнера_> ПродуктыПартнера_ { get; set; }
        public virtual DbSet<Продукция_> Продукция_ { get; set; }
        public virtual DbSet<СоставПродукции_> СоставПродукции_ { get; set; }
        public virtual DbSet<Тип_Материала_> Тип_Материала_ { get; set; }
        public virtual DbSet<ТипПартнера_> ТипПартнера_ { get; set; }
        public virtual DbSet<ТипПродукции_> ТипПродукции_ { get; set; }
    }
}
