//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материал_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Материал_()
        {
            this.СоставПродукции_ = new HashSet<СоставПродукции_>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Тип_Материала { get; set; }
    
        public virtual Тип_Материала_ Тип_Материала_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставПродукции_> СоставПродукции_ { get; set; }
    }
}
