//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Партнеры_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Партнеры_()
        {
            this.ПродуктыПартнера_ = new HashSet<ПродуктыПартнера_>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Тип_партнера { get; set; }
        public string Наименование_партнера { get; set; }
        public string Директор { get; set; }
        public string Электронная_почта_партнера { get; set; }
        public string Телефон_партнера { get; set; }
        public string Юридический_адрес_партнера { get; set; }
        public string ИНН { get; set; }
        public Nullable<double> Рейтинг { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродуктыПартнера_> ПродуктыПартнера_ { get; set; }
    }
}
