//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция_()
        {
            this.ПродуктыПартнера_ = new HashSet<ПродуктыПартнера_>();
            this.СоставПродукции_ = new HashSet<СоставПродукции_>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Тип_продукции { get; set; }
        public string Наименование_продукции { get; set; }
        public string Артикул { get; set; }
        public Nullable<double> Минимальная_стоимость_для_партнера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродуктыПартнера_> ПродуктыПартнера_ { get; set; }
        public virtual ТипПродукции_ ТипПродукции_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставПродукции_> СоставПродукции_ { get; set; }
    }
}
