//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тип_Материала_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тип_Материала_()
        {
            this.Материал_ = new HashSet<Материал_>();
        }
    
        public int Код { get; set; }
        public string Тип_материала { get; set; }
        public Nullable<double> Процент_брака_материала { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Материал_> Материал_ { get; set; }
    }
}
